version: '2'

services:
  test_api:
    build: .
    volumes:
      - .:/webapps
    command: ["./run_tests.sh"]
    environment:
      - PYTHONWARNINGS=ignore
      - DJANGO_SETTINGS_MODULE=users_posts.settings_test
      - SECRET_KEY=test_secret_key
      - ALLOWED_HOSTS=127.0.0.1, .localhost
